//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevDaysApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class devDaysSQLEntities : DbContext
    {
        public devDaysSQLEntities()
            : base("name=devDaysSQLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductCategory> ProductCategories { get; set; }

        public System.Data.Entity.DbSet<DevDaysApp.Models.ProductsFromTable> ProductsFromTables { get; set; }

        public System.Data.Entity.DbSet<DevDaysApp.Models.ProductsFromCosmos> ProductsFromCosmos { get; set; }
    }
}
